CREATE DATABASE STU_FAC;
USE STU_FAC;
CREATE TABLE STUDENT(
	SNUM INT PRIMARY KEY,
    SNAME VARCHAR(30) NOT NULL,
    MAJOR VARCHAR(20) NOT NULL,
    LVL VARCHAR(2) NOT NULL,
    AGE INT(2) NOT NULL);
CREATE TABLE CLASS(
	CNAME VARCHAR(20) NOT NULL,
    MEETS_AT TIME,
    ROOM VARCHAR(10),
    FID INT(10) NOT NULL);
CREATE TABLE ENROLLED(
	SNUM INT PRIMARY KEY,
    CNAME VARCHAR(20) NOT NULL);
CREATE 